### ISSUE TITLE
Party Achievements from Events

### ISSUE THREAD

**Issue by Serneum** [teamducro/gloomhaven-storyline#87] opened 2020-11-03 04:01 UTC
My group unlocked a Party Achievement tonight that came from a City Event. I did a quick search and didn't see it referenced in the codebase at all, so this may just be a feature request. How do we add party achievements that come from events?

**Comment by dducro** [comment] 2020-11-03 09:24
This is a duplicate of #59. I intend to implement this at some point.
Initially I didn't add the achievements that had no effect on the storyline.

**Closed by dducro** 2020-11-03 09:24 UTC
Labels: enhancement

**Comment by dducro** [comment] 2020-11-18 22:43
This is available in the current version! 🎉
